### PR TITLE
Components and Interactive

### PR DESCRIPTION
**Pull request by Lul-Abdifan**
In this Milestone, I have done the following
-  Delete all the boilerplate from Create React App
 -  Create Button component that get data from data button file
    -  Add a function that renders Calculator UI
-  Update Calculator component
 -  Update Styles for Calculator UI
-  Test it in the browser

I appreciate your understanding and patience. If you have any questions or concerns, please don't hesitate to reach out to me at @Lul-Abdifan.

### CODE REVIEW

**Review by julie-ify — CHANGES_REQUESTED** [review]
## Hi @Lul-Abdifan,

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] Kindly remove these generated files that will not be needed

tysa
hys

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Lul-Abdifan** [comment]
@julie-ify I appreciate your feedback. Some files are required for testing tasks for the coming projects . That is why I didn't delete.

Thank you for your reviewing and approval.Happy Coding :smile:

**Review by DammyShittu — APPROVED** [review]
Hi @Lul-Abdifan,

## APPROVED 🟢

## Highlights
✔️ Removal of unnecessary files

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Lul-Abdifan** [comment]
Hello, @DammyShittu  I appreciate your time in reviewing and approving. Happy Coding  :smile: :smile:

**Pull request merged**
