### PR TITLE
React setup

### PR DESCRIPTION
**Pull request by Lul-Abdifan**
### In this branch, I have done the following tasks:-
- Create react setup
- Install linters configuration
- Delete unnecessary files

I appreciate your time .I am here @Lul-Abdifan If you have any questions. :+1: :+1:  Happy Coding :smile:

### CODE REVIEW

**Review by mikethreels — CHANGES_REQUESTED** [review]
Hi Hope, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that isn't using the [readme template from Microverse](https://github.com/microverseinc/readme-template), please make sure to adjust this in your project before requesting another review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Lul-Abdifan** [comment]
@mikethreels I unintentionally left out the information that my update will be directed toward Microverse. I appreciate your constructive feedback. :smile: Happy Coding :smile: :smile:

**Review by levy002 — APPROVED** [review]
### Hello @Lul-Abdifan 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Status: APPROVED :fire:  :fire: 

## Highlights
- No linter errors :heavy_check_mark: 
- App is running well as expected :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Lul-Abdifan** [comment]
@levy002  I am grateful for the effort put into reviewing and approving. :smile: :desktop_computer:

**Pull request merged**
